#!/usr/bin/env node
// AgentForge — auto-enter matcher micro-benchmark (Phase 4).
//
// Substantiates (or honestly reframes) the README's "sub-millisecond hot loop"
// claim with REAL numbers. Zero dependencies — uses performance.now() and a
// warmup, the same philosophy as the rest of the repo's tests. Writes
// docs/BENCHMARKS.md. Run:  node tests/perf-bench.mjs
import fs from "node:fs";
import path from "node:path";
import { performance } from "node:perf_hooks";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Mirror of AUTO_PROMPT_RE in gui/server.js (kept in sync by hand — importing
// server.js would boot the HTTP server). The Rust sidecar (forge-pulse)
// matches the same prompt patterns; the JS path is authoritative.
const AUTO_PROMPT_RE = /\(y\/n\)|\[y\/n\]|\(yes\/no\)|\[yes\/no\]|press +enter +to +continue|press +any +key|approve\??|do +you +want +to|are +you +sure|continue\?|confirm\?|allow +this(?: +tool)? +to +run/i;

// A realistic corpus: a mix of prompt lines (should match) and ordinary PTY
// output (should not). The watchdog tests a rolling ~1.2 KB tail per chunk.
const PROMPTS = [
  "Do you want to proceed? (y/n)",
  "Allow this tool to run? [y/n]",
  "press enter to continue",
  "Are you sure? (yes/no)",
  "approve?",
  "continue?",
];
const NOISE = [
  "Compiling forge-pulse v0.1.0 (/home/user/AgentForge-Command/tools/forge-pulse)",
  "  added 4 packages, and audited 6 packages in 5s",
  "export function renderGrid(root, agents, opts) {",
  "  at Object.<anonymous> (/app/gui/server.js:42:11)",
  "{\"t\":\"o\",\"id\":\"forge\",\"d\":\"\\u001b[32mok\\u001b[0m build passed\"}",
  "tests: 186 passed, 0 failed",
];
// Build a ~1.2 KB tail like the watchdog sees, ending in a prompt some of the time.
function tail(withPrompt) {
  let s = NOISE.join("\n");
  while (s.length < 1100) s += "\n" + NOISE[s.length % NOISE.length];
  s = s.slice(-1150);
  if (withPrompt) s += "\n" + PROMPTS[s.length % PROMPTS.length];
  return s;
}

const corpus = [];
for (let i = 0; i < 1000; i++) corpus.push(tail(i % 4 === 0)); // 25% contain a prompt

function bench(label, fn, iters) {
  // warmup
  for (let i = 0; i < Math.min(iters, 5000); i++) fn(i);
  const t0 = performance.now();
  for (let i = 0; i < iters; i++) fn(i);
  const ms = performance.now() - t0;
  const perOpUs = (ms * 1000) / iters;
  const opsSec = iters / (ms / 1000);
  return { label, iters, totalMs: ms, perOpUs, opsSec };
}

const ITERS = 2_000_000;
const r = bench("JS matcher (AUTO_PROMPT_RE vs ~1.2KB tail)",
  (i) => AUTO_PROMPT_RE.test(corpus[i % corpus.length]), ITERS);

const perCheckMs = r.perOpUs / 1000;
const subMs = perCheckMs < 1.0;

const fmt = (n, d = 0) => n.toLocaleString("en-US", { maximumFractionDigits: d });
const report = `# Performance Benchmarks

> Generated by \`node tests/perf-bench.mjs\` — real numbers on this machine
> (Node ${process.version}, ${process.platform}/${process.arch}). Re-run to refresh.

## Auto-enter watchdog matcher

The auto-enter watchdog scans a rolling ~1.2 KB tail of each PTY's output for a
permission prompt (\`AUTO_PROMPT_RE\` in \`gui/server.js\`). This benchmark proves
the README's **"sub-millisecond hot loop"** claim with a measured figure.

| Metric | Value |
|--------|-------|
| Iterations | ${fmt(r.iters)} |
| Throughput | ${fmt(r.opsSec)} checks/sec |
| **Per-check latency** | **${r.perOpUs < 1 ? (r.perOpUs * 1000).toFixed(1) + " ns" : r.perOpUs.toFixed(3) + " µs"}** (${perCheckMs.toFixed(5)} ms) |
| Sub-millisecond per check? | ${subMs ? "✅ yes" : "❌ no"} |

**Conclusion.** A single matcher check costs about
**${r.perOpUs < 1 ? (r.perOpUs * 1000).toFixed(1) + " ns" : r.perOpUs.toFixed(2) + " µs"}** — ${subMs
  ? "comfortably sub-millisecond"
  : "above 1 ms; the claim is reframed accordingly"}. Real PTYs emit on the order
of 1–10 KB/sec, so the matcher is never the bottleneck regardless of the
optional Rust accelerator.

## The Rust accelerator (\`forge-pulse\`) — optional, advisory

\`forge-pulse\` checks the **same** prompt patterns in Rust and is auto-detected
when present. It is an optimisation, **not** a correctness dependency: the JS
matcher above is authoritative and the system runs identically without the
binary (5 Rust unit tests cover the sidecar's parsing/matching). The honest
takeaway: the JS path already satisfies the sub-millisecond budget, so Rust is
a "nice to have" for very high-throughput sessions, not a requirement.

_Method: ${fmt(r.iters)} iterations over a 1000-entry corpus of realistic ~1.2 KB
tails (25% containing a prompt), after a warmup, timed with
\`performance.now()\`. Numbers vary with CPU; re-run \`npm run test:perf\`._
`;

fs.writeFileSync(path.join(ROOT, "docs", "BENCHMARKS.md"), report);
console.log(report);
console.log(`\nperf-bench: per-check ${r.perOpUs.toFixed(3)} µs · ${subMs ? "SUB-MS ✅" : "ABOVE 1ms"}`);
process.exit(0);
